# Generated by Django 2.2.5 on 2019-12-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('Book_author', models.CharField(max_length=100)),
                ('Publication', models.CharField(max_length=100)),
                ('PublishedDate', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=100)),
                ('Book_author', models.CharField(max_length=100)),
                ('IssuedTo', models.CharField(max_length=100)),
                ('IssuedDate', models.DateField(max_length=100)),
            ],
        ),
    ]
