# Generated by Django 2.2.5 on 2019-12-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='BookName',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='Book_author',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='Book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
    ]
