# Generated by Django 2.2.5 on 2019-12-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191222_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.CharField(max_length=100)),
                ('BookAuthor', models.CharField(blank=True, max_length=100, null=True)),
                ('BookPublication', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='IssuedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
