# Generated by Django 2.2.5 on 2020-01-18 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20191223_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 21, 0, 4, 352274)),
        ),
    ]
