# Generated by Django 2.2.5 on 2020-01-18 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_issuedbook_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 21, 1, 16, 301594)),
        ),
    ]
