# Generated by Django 2.2.5 on 2020-02-15 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20200215_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedbook',
            old_name='Book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='requestbook',
            old_name='Book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='IssuedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 17, 49, 17, 629157)),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 17, 49, 17, 629157)),
        ),
    ]
