# Generated by Django 2.2.5 on 2020-02-15 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20200215_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedbook',
            old_name='book',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='requestbook',
            old_name='book',
            new_name='Book',
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='IssuedDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 17, 51, 26, 325332)),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='ReturnDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 17, 51, 26, 325332)),
        ),
    ]
