# Generated by Django 2.2.5 on 2020-01-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_studentsemester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentFaculty',
            field=models.CharField(choices=[('BCA', 'BCA'), ('Bsc.CSIT', 'Bsc.CSIT')], default='', max_length=10),
        ),
    ]
