# Generated by Django 2.2.5 on 2020-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20200215_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='Semester',
            field=models.CharField(choices=[('1st Sem', '1st Sem'), ('2st Sem', '2st Sem'), ('3st Sem', '3st Sem'), ('4st Sem', '4st Sem'), ('5st Sem', '5st Sem'), ('6st Sem', '6st Sem'), ('7st Sem', '7st Sem'), ('8st Sem', '8st Sem')], max_length=50),
        ),
    ]
