# Generated by Django 2.2.5 on 2020-02-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20200215_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentSemester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semester',
            name='Semester',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
