# Generated by Django 2.2.5 on 2020-02-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20200215_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Student_id',
        ),
    ]
